# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='M', max_length=5),
            preserve_default=False,
        ),
    ]
