# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0002_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
