# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0003_student_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_picture',
            new_name='poza_profil',
        ),
    ]
