# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0004_auto_20180226_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='poza_profil',
            field=models.FileField(default='1', upload_to=''),
        ),
    ]
