# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0005_auto_20180228_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_uid', models.CharField(max_length=30)),
                ('to_uid', models.CharField(max_length=30)),
                ('mesaj', models.CharField(max_length=600)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
            ],
        ),
    ]
