# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0007_coleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzie',
            name='calificativ',
            field=models.IntegerField(default=1),
        ),
    ]
