# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0010_student_cod_reset_parola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartizare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_matricol', models.CharField(max_length=30)),
                ('camin', models.CharField(max_length=20)),
            ],
        ),
    ]
