# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0011_repartizare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cod_reset_parola',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
