# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0012_auto_20180319_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferinte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_matricol', models.CharField(max_length=30)),
                ('uid_preferinta', models.CharField(max_length=30)),
                ('importanta', models.IntegerField()),
            ],
        ),
    ]
