# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0013_preferinte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferinte',
            new_name='Preferinta',
        ),
    ]
