# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0014_auto_20180421_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimeStabila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camin', models.CharField(max_length=20)),
                ('numar_camera', models.IntegerField()),
                ('coleg1', models.CharField(max_length=30)),
            ],
        ),
    ]
