# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0015_multimestabila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_camin', models.CharField(max_length=20)),
                ('numar_camera', models.IntegerField()),
                ('coleg1', models.CharField(max_length=30)),
                ('coleg2', models.CharField(max_length=30)),
                ('coleg3', models.CharField(blank=True, max_length=30)),
                ('coleg4', models.CharField(blank=True, max_length=30)),
                ('coleg5', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MultimeStabila',
        ),
    ]
