# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0016_auto_20180514_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimeStabila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleg1', models.CharField(max_length=30)),
                ('coleg2', models.CharField(max_length=30)),
                ('coleg3', models.CharField(blank=True, max_length=30)),
                ('coleg4', models.CharField(blank=True, max_length=30)),
                ('coleg5', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='camin',
            name='coleg1',
        ),
        migrations.RemoveField(
            model_name='camin',
            name='coleg2',
        ),
        migrations.RemoveField(
            model_name='camin',
            name='coleg3',
        ),
        migrations.RemoveField(
            model_name='camin',
            name='coleg4',
        ),
        migrations.RemoveField(
            model_name='camin',
            name='coleg5',
        ),
        migrations.AddField(
            model_name='camin',
            name='facultate',
            field=models.CharField(blank=True, choices=[('Biologie', 'Biologie'), ('Chimie', 'Chimie'), ('Drept', 'Drept'), ('Economie și Administrarea Afacerilor', 'Economie și Administrarea Afacerilor'), ('Educație fizică și Sport', 'Educație fizică și Sport'), ('Filosofie și Științe Social-Politice', 'Filosofie și Științe Social-Politice'), ('Fizică', 'Fizică'), ('Geografie și Geologie', 'Geografie și Geologie'), ('Informatică', 'Informatică'), ('Istorie', 'Istorie'), ('Litere', 'Litere'), ('Matematică', 'Matematică'), ('Psihologie și Științe ale Educației', 'Psihologie și Științe ale Educației'), ('Teologie Ortodoxă', 'Teologie Ortodoxă'), ('Teologie Romano-Catolică', 'Teologie Romano-Catolică')], max_length=40),
        ),
        migrations.AddField(
            model_name='multimestabila',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stable.Camin'),
        ),
    ]
