# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0018_auto_20180514_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimestabila',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='multimestabila',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stable.Camin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='numar_matricol',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='camin',
            unique_together=set([('nume_camin', 'numar_camera')]),
        ),
        migrations.AlterUniqueTogether(
            name='coleg',
            unique_together=set([('coleg1', 'coleg2')]),
        ),
        migrations.AlterUniqueTogether(
            name='preferinta',
            unique_together=set([('numar_matricol', 'uid_preferinta')]),
        ),
        migrations.AlterUniqueTogether(
            name='recenzie',
            unique_together=set([('from_uid', 'to_uid')]),
        ),
        migrations.AlterUniqueTogether(
            name='repartizare',
            unique_together=set([('numar_matricol', 'camin')]),
        ),
    ]
