# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0019_auto_20180514_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimestabila',
            name='camera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stable.Camin'),
        ),
    ]
