# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0020_auto_20180514_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facultate',
            field=models.CharField(choices=[('Biologie', 'Biologie'), ('Chimie', 'Chimie'), ('Drept', 'Drept'), ('Economie și Administrarea Afacerilor', 'Economie și Administrarea Afacerilor'), ('Educație fizică și Sport', 'Educație fizică și Sport'), ('Filosofie și Științe Social-Politice', 'Filosofie și Științe Social-Politice'), ('Fizică', 'Fizică'), ('Geografie și Geologie', 'Geografie și Geologie'), ('Informatică', 'Informatică'), ('Istorie', 'Istorie'), ('Litere', 'Litere'), ('Matematică', 'Matematică'), ('Psihologie și Științe ale Educației', 'Psihologie și Științe ale Educației'), ('Teologie Ortodoxă', 'Teologie Ortodoxă'), ('Teologie Romano-Catolică', 'Teologie Romano-Catolică')], default='Informatică', max_length=40),
            preserve_default=False,
        ),
    ]
