# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0022_auto_20180516_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='camin',
            name='locuri',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
