# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0023_camin_locuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartizare',
            name='repartizare_camera',
            field=models.BooleanField(default=False),
        ),
    ]
