# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0024_repartizare_repartizare_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimestabila',
            name='coleg2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
