# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0025_auto_20180519_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_expeditor', models.CharField(max_length=40)),
                ('deadline', models.DateField(blank=True)),
                ('titlu', models.CharField(max_length=100)),
                ('mesaj', models.CharField(max_length=1000)),
            ],
        ),
    ]
