# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0027_remove_anunt_nume_expeditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='prenume',
        ),
        migrations.AlterField(
            model_name='student',
            name='an',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grupa',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='nume',
            field=models.CharField(max_length=70),
        ),
    ]
