# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0028_auto_20180601_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='facultate',
            field=models.CharField(max_length=40),
        ),
    ]
