# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0030_auto_20180601_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camin',
            name='nume_camin',
            field=models.CharField(max_length=30),
        ),
    ]
