# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0032_auto_20180601_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camin',
            name='facultate',
            field=models.CharField(blank=True, choices=[('Biologie', 'Biologie'), ('Chimie', 'Chimie'), ('Drept', 'Drept'), ('Economie si Administrarea Afacerilor', 'Economie și Administrarea Afacerilor'), ('Educatie fizica si Sport', 'Educație fizică și Sport'), ('Filosofie si Stiinte Social-Politice', 'Filosofie și Științe Social-Politice'), ('Fizica', 'Fizică'), ('Geografie si Geologie', 'Geografie și Geologie'), ('Informatica', 'Informatică'), ('Istorie', 'Istorie'), ('Litere', 'Litere'), ('Matematica', 'Matematică'), ('Psihologie si Stiinte ale Educatiei', 'Psihologie și Științe ale Educației'), ('Teologie Ortodoxa', 'Teologie Ortodoxă'), ('Teologie Romano-Catolica', 'Teologie Romano-Catolică')], max_length=40),
        ),
        migrations.AlterField(
            model_name='camin',
            name='nume_camin',
            field=models.CharField(choices=[('C1', 'Cămin C1'), ('C2', 'Cămin C2'), ('C3', 'Cămin C3'), ('C4', 'Cămin C4'), ('C5', 'Cămin C5'), ('C6', 'Cămin C6'), ('C7', 'Cămin C7'), ('C8', 'Cămin C8'), ('C10', 'Cămin C10'), ('C11', 'Cămin C11'), ('C12', 'Cămin C12'), ('C13', 'Cămin C13'), ('Gaudeamus', 'Hotelul studenţesc Gaudeamus'), ('Akademos', 'Hotelul studenţesc Akademos'), ('Buna Vestire', 'Cămin „Buna Vestire"')], max_length=30),
        ),
    ]
