# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0033_auto_20180601_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleg',
            name='nume_camin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
