# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0034_coleg_nume_camin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunt',
            name='deadline',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
    ]
