# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0035_auto_20180603_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunt',
            name='deadline',
            field=models.DateField(blank=True, default='2500-12-31'),
        ),
    ]
